FROM golang:1.23.0-alpine3.20

#安装编译需要的环境gcc等，使用阿里云加速
RUN apk add --repository https://mirrors.aliyun.com/alpine/v3.20/main build-base
#安装编译需要的环境gcc等
RUN apk add build-base

##docker build -t cgo-mck:mck  .